### ISSUE TITLE
On cygwin, make fails, unable to make win/resources.rc

### ISSUE THREAD

**Issue by ofaurax** [framon/cntlm#1]
From the cygwin shell:

```
$ ./configure && make
Using /usr/bin/gcc to compile Cntlm
Checking endian... little endian
Checking strdup... yes
Checking socklen_t... yes
Checking gethostname... LAPTOP27
make: *** No rule to make target 'win/resources.rc', needed by 'win/resources.o'.  Stop.
```

I can easily test things from the client side.

**Comment by framon** [comment]
This repository was cloned from Ubuntu, so I do not expect it to work in Cygwin.
I have no Windows environment, but I will make an effort to fix it.

**Comment by ofaurax** [comment]
It builds if I disable the compilation of win/resources.rc in the Makefile

**Comment by framon** [comment]
Please, try to build from the branch make-fails-on-cygwin

**Comment by ofaurax** [comment]
Another error:

```
$ ./configure && make
Using /usr/bin/gcc to compile Cntlm
Checking endian... little endian
Checking strdup... yes
Checking socklen_t... yes
Checking gethostname... INSIDE2498
Adding EXE resources
windres: can't open icon file `win/cntlm.ico': No such file or directory
Makefile:126: recipe for target 'win/resources.o' failed
make: *** [win/resources.o] Error 1
```

**Comment by framon** [comment]
Sorry, but I can't check if build success.
I have made another push. Please, try again.

**Comment by ofaurax** [comment]
It builds on cygwin now, thank you.
However, the exe produced exit after some lines...
I'll investigate and try to provide a patch.
Thank you
